name: SmokeSignal
favicon: null
layout_spectrum: 0.49132
typography_spectrum: 0.52229
title: 'Helping businesses thrive in the new millennial world. '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3e3b36'
    - '#55595c'
    - '#acbccb'
    - '#76828d'
    - '#cad3da'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.1713660650420934
  rhythmicContrast: 0.2494865208864212
purpose: []
